// packages/frontend/src/pages/LoginPage.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '../store/authStore';
import { Loader2 } from 'lucide-vue-next';
import AuthLayout from '../components/AuthLayout.vue';
import ErrorAlert from '../components/ErrorAlert.vue';

const email = ref('');
const password = ref('');
const authStore = useAuthStore();
const router = useRouter();

async function handleSubmit() {
  try {
    await authStore.login(email.value, password.value);
    router.push('/dashboard');
  } catch {
    // Error is handled by the store
  }
}
</script>

<template>
  <AuthLayout subtitle="Learn languages through personalized reading">
    <div class="card p-8">
      <h2 class="text-2xl font-semibold text-center mb-6">Welcome back</h2>

      <ErrorAlert v-if="authStore.error" :error="authStore.error" @dismiss="authStore.clearError()" />

      <form @submit.prevent="handleSubmit" class="space-y-4">
        <div>
          <label for="email" class="block text-sm font-medium text-gray-700 mb-1">Email</label>
          <input
            id="email"
            type="email"
            v-model="email"
            class="input"
            placeholder="you@example.com"
            required
          />
        </div>

        <div>
          <label for="password" class="block text-sm font-medium text-gray-700 mb-1">Password</label>
          <input
            id="password"
            type="password"
            v-model="password"
            class="input"
            placeholder="••••••••"
            required
          />
        </div>

        <button type="submit" :disabled="authStore.isLoading" class="btn btn-primary w-full py-3">
          <template v-if="authStore.isLoading">
            <Loader2 class="w-5 h-5 animate-spin mr-2" />
            Signing in...
          </template>
          <template v-else>Sign in</template>
        </button>
      </form>

      <p class="text-center text-gray-600 mt-6">
        Don't have an account?
        <RouterLink to="/register" class="text-primary-600 hover:text-primary-700 font-medium">
          Sign up
        </RouterLink>
      </p>
    </div>
  </AuthLayout>
</template>

// packages/frontend/src/pages/LoginPage.tsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuthStore } from '../store/authStore';
import { BookOpen, Loader2, AlertCircle } from 'lucide-react';

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const { login, isLoading, error, clearError } = useAuthStore();
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await login(email, password);
      navigate('/dashboard');
    } catch {
      // Error is handled by the store
    }
  };

  return (
    <div className="min-h-dvh flex items-center justify-center bg-gradient-to-br from-primary-50 to-accent-50 px-4">
      <div className="w-full max-w-md">
        {/* Logo */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-primary-600 text-white mb-4">
            <BookOpen className="w-8 h-8" />
          </div>
          <h1 className="text-3xl font-bold text-gray-900">Duopara</h1>
          <p className="text-gray-600 mt-2">Learn languages through personalized reading</p>
        </div>

        {/* Login form */}
        <div className="card p-8">
          <h2 className="text-2xl font-semibold text-center mb-6">Welcome back</h2>
          
          {error && (
            <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg flex items-center gap-2 text-red-700">
              <AlertCircle className="w-5 h-5 flex-shrink-0" />
              <span className="text-sm">{error}</span>
              <button onClick={clearError} className="ml-auto text-red-500 hover:text-red-700">
                &times;
              </button>
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1">
                Email
              </label>
              <input
                id="email"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="input"
                placeholder="you@example.com"
                required
              />
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">
                Password
              </label>
              <input
                id="password"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="input"
                placeholder="••••••••"
                required
              />
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="btn btn-primary w-full py-3"
            >
              {isLoading ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin mr-2" />
                  Signing in...
                </>
              ) : (
                'Sign in'
              )}
            </button>
          </form>

          <p className="text-center text-gray-600 mt-6">
            Don't have an account?{' '}
            <Link to="/register" className="text-primary-600 hover:text-primary-700 font-medium">
              Sign up
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
